version: '3'
services:
  pg:
    container_name: pg
    image: postgres
    restart: always
    ports:
      - "5355:5432"
    environment:
      POSTGRES_DB: TgBotDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SECRET
  app:
    container_name: TelegramBotMOEVM
    build: .
    ports:
      - "9000:8080"
    depends_on:
      - pg
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/TgBotDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: SECRET
